name: Desafio um

on:
  workflow_dispatch:
    inputs:
      image:
        description: 'Informe a imagem e a tag que deseja utilizar (image:tag)'
        required: true
        type: string

jobs:
  desafio-um:
    runs-on: ubuntu-latest

    steps:
      - name: Download da imagem informada
        run: docker pull ${{ github.event.inputs.image }}
      
      - name: Verifica se a imagem foi baixada
        run: docker images